# ============ PERFIL DEV (H2 Archivo) ============
server.port=8082

# H2 Configuration (Modo Archivo)
# 'file:./data/parqueaderodb' crea una carpeta 'data' en la raiz del proyecto y guarda la DB ahi.
# 'AUTO_SERVER=TRUE' permite abrir la consola H2 mientras la app corre.
spring.datasource.url=jdbc:h2:file:./data/parqueaderodb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console