version: "3.8"

services:
  # Servicio de Base de Datos PostgreSQL
  postgres-db:
    image: postgres:15
    container_name: parqueadero-postgres
    environment:
      POSTGRES_DB: parqueaderodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # Permite conectar DBeaver/PgAdmin desde tu PC
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos
    networks:
      - parqueadero-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de tu Aplicación Spring Boot
  app-backend:
    build: .
    container_name: parqueadero-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=pro
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/parqueaderodb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres # Cambiar por una clave segura en producción
      
      # SEGURIDAD: Define estas variables antes de arrancar en producción
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      
      # CORS: Agrega tu dominio real aquí cuando lo sepas (separado por comas)
      - CORS_ORIGINS=http://localhost:4200
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - parqueadero-net

volumes:
  postgres_data:

networks:
  parqueadero-net:
