# ============ PERFIL PRO (PostgreSQL) ============
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/parqueaderodb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# En produccion usamos 'update' o 'validate' para no borrar datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false