# ============ PERFIL PRO (PostgreSQL) ============
# Puerto para Producción
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/parqueaderodb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# En produccion usamos 'update' o 'validate' para no borrar datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Admin User Configuration
admin.user.username=admin
admin.user.password=supersecretpassword

# Configuración de cupos iniciales (Valores para Producción)
parqueadero.cupos.carro=50
parqueadero.cupos.moto=50
parqueadero.cupos.bicicleta=20