# ============ PERFIL DEV (H2) ============
# Puerto para Desarrollo
server.address=0.0.0.0
server.port=8082

spring.datasource.url=jdbc:h2:mem:parqueaderodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Admin User
admin.user.username=admin
admin.user.password=admin123

# Configuración de cupos iniciales (Valores para Desarrollo)
parqueadero.cupos.carro=10
parqueadero.cupos.moto=10
parqueadero.cupos.bicicleta=10
parqueadero.cupos.camion=5

# Logging - nivel DEBUG en desarrollo
logging.level.com.parqueadero=DEBUG
