# ===============================================================
# =      CONFIGURACIÓN PARA ENTORNO DE DESARROLLO (DEV)         =
# ===============================================================

# Puerto del servidor
server.port=8082

# Configuración de la Base de Datos H2 (en memoria)
spring.datasource.url=jdbc:h2:mem:parqueaderodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate: 'create-drop' crea el esquema al iniciar y lo borra al detener. Ideal para dev.
spring.jpa.hibernate.ddl-auto=create-drop

# JWT Secret - Usa un valor diferente y más seguro para producción
jwt.secret=NThkYjQxYjM0YjFjYmY4YjU2ZTRhY2M5YjU2ZTRhY2M5YjU2ZTRhY2M5YjU2ZTRhY2M5
jwt.expiration=86400000 # 24 horas

# Configuración de cupos iniciales
parqueadero.cupos.carro=10
parqueadero.cupos.moto=10
parqueadero.cupos.bicicleta=10

# Admin User Configuration
admin.user.username=admin
admin.user.password=admin123